Java Home Assignment  (Collections & Stream API)
epolevikov/hh-school-2022-java-collections-stream pull request #1
Opened 2022-12-11 09:45 UTC by epolevikov

## Task 1
Время работы метода `findOrderedPersons` – `T + O(N)`, где `T` – время работы метода `findPersons`, `N` – количество элементов в коллекции `personIds`. На первом шаге строим `Map`, которая для `id` персоны возвращает саму персону, на 2м шаге используем эту коллекцию, чтобы преобразовать список `id` персон в список персон. Операции вставки и удаления для `Map` работают за `O(1)`, поэтому общее время работы этих двух шагов линейное.
## Task 8
### Метод getNames
В изначальной версии вызывается метод `remove` у передаваемого списка, который меняет коллекцию. Если вызвать такой метод 2 раза подряд передав ссылку на одинаковую коллекцию, то метод вернет разные результаты. К тому же для `ArrayList` такая операция займет дополнительно `O(N)` времени. Переписал метод с использованием стримов. Новый код не меняет исходную коллекцию и читается проще.
### Метод getDifferentNames
В изначальной версии вызов `distinct` лишний, так как в конце мы собираем в `Set`, который и так содержит только уникальные элементы. Ну и стримы здесь ни к чему, можно просто в констуктор `Set` передать коллекцию всех имен, тогда как раз и получим множество уникальных имен.
### Метод convertPersonToString
Переписал с использованием стримов (логику построения полного имени не менял). Такой код читается проще, а также избавляет нас от многочисленных веток `if` и проверок на `null`. В изначальной версии также есть такая проблема: если `secondName == null`, то в имени получим пробел в самом начале. В новой версии этой проблемы нет.
### Метод getPersonNames
Тут кажется всё ок, просто переписал на стримы, так проще и понятнее.
### Метод  hasSamePersons
Тут тоже всё ок, использовал стримы. Проще и понятнее.
### Метод countEven
Вместо переменной `count` использовал метод стрима `count()` для подсчета количества четных чисел. В целом потому, что не вижу необходимости использовать какие-то дополнильные переменные, если у стрима уже есть свой метод, который позволяет нам решить нашу задачу. Обновленный код проще и понятнее.

Также дописал тесты для Task1, Task3 и Task8.

2022-12-12 11:50 UTC, genroelgvozo requested changes

2022-12-12 13:51 UTC, epolevikov commented on src/main/java/tasks/Task6.java
> +          .map(areaId -> person.getFirstName() + " - " + areaNameForAreaId.get(areaId)))
Вынес логику в отдельный метод `getPersonDescription`.

2022-12-12 13:52 UTC, epolevikov commented on src/main/java/tasks/Task7.java
> +      .flatMap(company -> company.getVacancies().stream().map(Vacancy::getTitle))
Поправил

2022-12-13 06:44 UTC, genroelgvozo commented on src/main/java/tasks/Task8.java
> +    return persons1.stream().anyMatch(persons2::contains);
не только линкед, но и обычный ArrayList тоже будет за O(nm)
кстати есть метод Collections.disjoint, он там сам выбирает в какой коллекции contains делать, на основе типа. но не спасет если оба листы, тут можно конечно доппроверки и преобразования делать, но это смотря что нужно - скорость или память

2022-12-13 06:45 UTC, genroelgvozo approved these changes

2022-12-15 14:30 UTC, merged